### ISSUE TITLE
Bootstrapping Issue 

### ISSUE THREAD

**Issue by shahzeb79** [SAP/karma-ui5#222]
Hi Colleagues,
                     Recently i saw an issue while using karma runner for one of App. In this app we have some action to upload a file using fileUpload control and run tests. Team uses a path of file like :
`When.onTheObjectDesignPage.iChangeUploadFile("/hpa.cei.cpg.cnt.msg/localService/mockdata/files/resp-template-standard.html", "resp-template-standard.html");`

But somehow tests fails as it dont find this file. if we use something like
`When.onTheObjectDesignPage.iChangeUploadFile("/base/webapp/localService/mockdata/files/resp-template-standard.html", "resp-template-standard.html");`

Than it gets successfully found and tests become green. But than on safetynet which uses mvn runner it fails with /base/webapp.

This also happen in case of json files and html where we have paths like:

`<p><img src="/hpa.cei.cpg.cnt.msg/localService/mockdata/images/image1Thumbnail.jpg" alt="Image" title="Image" width="130" height="130" style="opacity: 1;" data-sap-hpa-ceimo-image="SMOImage" data-sap-hpa-ceimo-image-type="Dynamic" data-sap-hpa-ceimo-image-pers="\|%PI-CUAN_OFFER-CONTENT_SOURCE%\|" data-sap-hpa-ceimo-image-id="1525256829858778"></p>`

This also dont work in html files.

Can any one also faces some issue like this?

**Comment by codeworrior** [comment]
If tests are to be run in different environments, with different servers or deployment schemes, it is better not to use server absolute URLs (URLs starting with /) as those URLs always assume a certain deployment scheme.

J2EE server (like the Jetty used in the tests executed by Maven) usually deploy with a web context name (=== application name), so server URLs starting with the App name (`"/hpa.cei.cpg.cnt.msg/..."`) will work in that environment. But in other environments, the deployment might create a different URL (like the `"/base/..."` that you mentioned for Karma).

It is therefore recommended not to use server absolute URLs and rather use relative URLs. The problem is that relative URLs need to know where they are used from (the base URL to which they would be relative).

Another alternative for URLs that are created from JavaScript code in an UI5 environment is to use the `sap.ui.require.toUrl("...")` API to dynamically resolve the URL of a resource. But this requires that the resource has been mapped to UI5's resource name space (e.g. via resourceroots configuration). So at the end this requires another URL somewhere, using the first recommended alternative. But it can help to reduce the relative URLs to a single place and derive all others form that configuration.

**Comment by shahzeb79** [comment]
@codeworrior But how it will apply to json files and html files where we have "/hpa.cei.cpg.cnt.msg/...". 
these html and json files are loaded by mockserver

**Comment by codeworrior** [comment]
As long as the mock server (data) is used only from HTML pages that reside at the same nesting level (e.g. all 1 level deep or 2 levels deep in the folder hierarchy), then relative URLs still should work out. Trouble just starts when the relative URLs are meant to be used from pages on different nesting levels.

**Comment by codeworrior** [comment]
@shahzeb79 I was made aware of another possible solution: Karma allows to configure [proxies](http://karma-runner.github.io/5.0/config/configuration-file.html) that map from one URL (e.g. "/hpa.cei.cpg.cnt.msg/" to another one, e.g. "/base/"). You could use that feature to map the Maven URLs to the Karma URLs.

**Comment by shahzeb79** [comment]
@codeworrior Thanks alot for your comments, but we have one karma file for 2000+ apps, so every thing is pretty generic and i cannot unfortunately add proxy for one app in karma. i will try this solution somehow locally also
