### ISSUE TITLE
Server start failed on port 9876: Error: No provider for "framework:openui5"! (Resolving: framework:openui5)

### ISSUE THREAD

**Issue by PavlinaCherkezova** [SAP/karma-ui5#247]
I am trying to run grunt test on this sample app [openui5-sample-app-testing](https://github.com/vobu/openui5-sample-app-testing) and get an error: _Server start failed on port 9876: Error: No provider for "framework:openui5"! (Resolving: framework:openui5)._ 

**package.json** looks like this: 

```
{
	"name": "openui5-sample-app",
	"version": "0.2.0",
	"description": "Sample of an OpenUI5 app",
	"private": true,
	"scripts": {
		"start": "ui5 serve",
		"lint": "eslint webapp",
		"karma": "karma start",
		"karma-ci": "rimraf coverage && karma start karma-ci.conf.js",
		"watch": "npm run karma",
		"test": "npm run lint && npm run karma-ci",
		"build": "ui5 build -a --clean-dest",
		"build-self-contained": "ui5 build self-contained -a --clean-dest",
		"serve-dist": "ws --compress -d dist"
	},
	"dependencies": {
		"grunt-contrib-uglify": "^5.0.0"
	},
	"devDependencies": {
		"@ui5/cli": "^2.4.4",
		"eslint": "^7.9.0",
		"grunt": "^1.3.0",
		"grunt-connect-http-auth": "^0.1.2",
		"grunt-contrib-clean": "^2.0.0",
		"grunt-contrib-connect": "^2.0.0",
		"grunt-contrib-copy": "^1.0.0",
		"grunt-eslint": "^22.0.0",
		"grunt-karma": "^3.0.2",
		"grunt-openui5": "^0.17.0",
		"karma": "^5.2.2",
		"karma-chrome-launcher": "^3.1.0",
		"karma-coverage": "^2.0.3",
		"karma-qunit": "^4.1.1",
		"karma-ui5": "^2.3.0",
		"karma-webdriver-launcher": "^1.0.8",
		"local-web-server": "^4.2.1",
		"qunit": "^2.11.2",
		"rimraf": "^3.0.2"
	}
}
```

Similar to this bug I found [Related bug](https://github.com/SAP/karma-ui5/issues/96) and also tried the solution, but with no success.

**Comment by RandomByte** [comment]
Hey, the current [openui5-sample-app-testing](https://github.com/vobu/openui5-sample-app-testing) project (on branch `04_adv_mumbojambo`) uses a very old version of karma-ui5 (formerly known as karma-openui5) `0.2.3`.

Since you are upgrading this dependency to karmau-i5@2.3.0, you need to follow the [migration guide](https://github.com/SAP/karma-ui5/blob/master/docs/migrate-v1.md) to adapt the projects karma configuration as defined in the [Gruntfile](https://github.com/vobu/openui5-sample-app-testing/blob/afe1b1563ad02e6dff43d32c527ba2c2eb88e2d2/Gruntfile.js#L107).
