### ISSUE TITLE
Potentially vulnerable dependency marked-0.8.2.js

### ISSUE THREAD

**Issue by bhadana-rajesh** [SAP/karma-ui5#252]
Potentially vulnerable dependency marked-0.8.2.js

Please see https://github.com/markedjs/marked/commit/bd4f8c464befad2b304d51e33e89e567326e62e0

Karma UI5 - marked dependency should be upgraded
	karma-ui5
     		@ui5/project
			@ui5/logger
				escope
					jsdoc
                                            marked

**Comment by RandomByte** [comment]
Thanks for reporting.

The `marked` dependency is installed because it is a dependency of jsdoc@3.6.6 (currently the latest version of jsdoc). Also see: https://snyk.io/test/npm/jsdoc/3.6.6

Apparently jsdoc needs to actively upgrade the `marked` dependency in [their package.json](https://github.com/jsdoc/jsdoc/blob/3.6.6/package.json#L24). We can't upgrade the dependency in our projects.

Since the JSDoc part of `@ui5/builder` is not used in karma-ui5 I don't see any security concerns for this module. I also don't see how this type of vulnerability might affect a normal build using `@ui5/builder`.

If you want to resolve the audit warning, feel free to report this to the [JSDoc project](https://github.com/jsdoc/jsdoc/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).

Closing as the root cause is unrelated to karma-ui5.
